const CANDIDATE_INTERVIEW_CREATE = "CANDIDATE_INTERVIEW_CREATE";
const CANDIDATE_INTERVIEW_LIST = "CANDIDATE_INTERVIEW_LIST";
const CANDIDATE_INTERVIEW_EDIT = "CANDIDATE_INTERVIEW_EDIT";
export {
	CANDIDATE_INTERVIEW_CREATE,
	CANDIDATE_INTERVIEW_LIST,
	CANDIDATE_INTERVIEW_EDIT,
};
