const MANAGER = 0; // truong phong
const HR_MANAGER = 1; // truong phong nhan su
const HR = 2; // hr
const INTERVIEWER = 3; // nguoi phong van 

export const NOTIFICATION_TYPE = {
    "JOBREQUEST/CREATED": [HR],
    "JOBREQUEST/UPDATED": [HR_MANAGER],
    // "JOBREQUEST/DELETED": [],
    "JOBREQUEST/WAITING": [HR_MANAGER],
    "JOBREQUEST/APPROVED": [MANAGER],
    "JOBREQUEST/REJECTED": [MANAGER],

    "INTERVIEW/CREATED": [MANAGER, INTERVIEWER],

    "CANDIDATE/CREATED": [HR, HR_MANAGER],
    "CANDIDATE/UPDATED": [HR, HR_MANAGER],
    // "CANDIDATE/DELETED": [],

    "CANDIDATE_INTERVIEW/CREATED": [MANAGER, HR_MANAGER, HR],
    "CANDIDATE_INTERVIEW/UPDATED": [MANAGER, HR_MANAGER, HR]
}
