const GET_CANDIDATE = "GET_CANDIDATE";
const CREATE_CANDIDATE = "CREATE_CANDIDATE";
const EDIT_CANDIDATE = "EDIT_CANDIDATE";
const DELETE_CANDIDATE = "DELETE_CANDIDATE";
const REJECT = "REJECT";
export {
	GET_CANDIDATE,
	CREATE_CANDIDATE,
	DELETE_CANDIDATE,
	EDIT_CANDIDATE,
	REJECT,
};
